"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

# Step 1: Initialize a list
# Step 2: Run a while loop to get a Fibonacci sequence until n = 4mil
# Step 3: Filter list for even values

# Initialize with placeholders
a = 1
b = 2
numbers = [a, b]
stillUnderLimit = True

# Populate list
while stillUnderLimit:
    c = a + b

    if c < 4000000:
        a = b
        b = c
        numbers.append(c)
    else:
        stillUnderLimit = False

# Filter list
even_numbers = []
for a in numbers:
    if a % 2 == 0:
        even_numbers.append(a)

print(sum(even_numbers))
